	for i in range(0, 1):
		#break
		if sino.objeto[i].Tipo == 1:
			print("Tipo: " + str(sino.objeto[i].Tipo))
			print("Nome: " + sino.objeto[i].Nome)
			print("Variavel: " + str(sino.objeto[i].Variavel))
			print("Index: " + str(sino.objeto[i].IndexObjecto))
			print("Digital: " + str(sino.objeto[i].Digital))
			print("X: " + str(sino.objeto[i].x))
			print("Y:" + str(sino.objeto[i].y))
			print("Texto ON: " + sino.objeto[i].TextoOn)
			print("Texto OFF: " + sino.objeto[i].TextoOff)
			print("Largura: " + str(sino.objeto[i].Largura))
			print("Altura: " + str(sino.objeto[i].Altura))
			print("Imagem Botao: " + sino.objeto[i].ImagemBotao)
			print("Imagem Posicao Botao: " + str(sino.objeto[i].ImagemPosicaoBotao))
			print("Ficheiro: " + sino.objeto[i].Ficheiro)
			print("Tipo de Animacao: " + str(sino.objeto[i].TipoDeAnimacao))
			print("Variavel Minima: " + str(sino.objeto[i].VariavelMin))
			print("Variavel Maxima: " + str(sino.objeto[i].VariavelMax))
			print("Separador de Milhares:" + str(sino.objeto[i].SeparadorDeMilhares))
			print("Texto:" + sino.objeto[i].Texto)
			print("Contorno: " + str(sino.objeto[i].Contorno))
			print("Tipo de Letra: " + sino.objeto[i].TipoDeLetraNome)
			print("Tamanho da Letra: " + str(sino.objeto[i].TipoDeLetraTamanho))
			print("Cor da Letra:" + str(sino.objeto[i].TipoDeLetraCor))
			print("Bold: " + str(sino.objeto[i].TipoDeLetraBold))
			print("Italico: " + str(sino.objeto[i].TipoDeLetraItalico))
			print("Sublinhado: " + str(sino.objeto[i].TipoDeLetraSublinhado))
			print("Cor do Fundo: " + str(sino.objeto[i].CorDoFundo))
			print("Enable: " + str(sino.objeto[i].Enable))
			print("Som ON: " + sino.objeto[i].SomOn)
			print("Som OFF: " + sino.objeto[i].SomOff)
			print("Casa Decimal: " + str(sino.objeto[i].CasaDecimal))
